### ISSUE TITLE
SouthKorea Map Issue

### ISSUE THREAD

**Issue by beizix** [amcharts/amcharts4-geodata#1]
Hello, I found that there is a issue when using geodata ( southKoreaLow.js or southKoreaHigh.js )

![image](https://user-images.githubusercontent.com/3313285/47341451-fc11b180-d6db-11e8-9dbe-a022e368f22d.png)

as above screenshot, you can find some empty areas. please fix those bugs.

**Comment by martynasma** [comment]
Thanks for the heads up!

We'll let you know when updated map is available.

**Comment by martynasma** [comment]
We've just released an updated version with South Korean map fixed.

Thanks again for bringing it to our attention!
