### ISSUE TITLE
Invalid data for South Africa

### ISSUE THREAD

**Issue by spec-art** [amcharts/amcharts4-geodata#14]
Trying to use the data for South Africa and found that there's some invalid data for the Western Cape province (id is ZA-WC) 

It seems the southAfrica sources (both High and Low) have the same issue. This can be viewed by looking to towards the bottom of https://github.com/amcharts/amcharts4-geodata/blob/master/dist/script/json/southAfricaHigh.json 

As mentioned this is also the case for the other data sources. I can't move past this because I have to use the center of each province for something like this https://www.amcharts.com/demos/map-image-drill-down/ but since there is a point so low down the center of WC is calculated to be in the ocean. 

Would it be possible to fix this or can you suggest a work around to be used in the mean time? 

![image](https://user-images.githubusercontent.com/53224960/77322665-bddb5000-6d1c-11ea-8b49-1424e814cbd4.png)

**Comment by martynasma** [comment]
Not sure what you are suggesting. Removing Western Cape islands from the map?

**Comment by spec-art** [comment]
Didn't realize they were part of WC. Sorry about that. I need to use it on a responsive drill-down map, (link in OP) so my issue is finding the center of the province to add the label. I worked around it by explicitly placing the label on coordinates.
