### ISSUE TITLE
Incorrect municipality names in Dominican Republic Municipality maps

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4-geodata#2]
A user reported that the following IDs have the wrong names associated with them in the dominicanRepublicMuniLow and dominicanRepublicMuniHigh maps:

DO-23-QQ - Quisquella should be changed to Quisqueya

DO-29-ES - Esperalvillo should be changed to Peralvillo

**Comment by martynasma** [comment]
Fixed in 4.0.16
