### ISSUE TITLE
US Congressional District Map with repeating ID

### ISSUE THREAD

**Issue by carmoreira** [amcharts/amcharts4-geodata#30]
It seems the Alabama state congressional district map has one region with a duplicated ID, causing issues when the map renders:

https://github.com/amcharts/amcharts4-geodata/blob/master/dist/script/json/region/usa/congressional/alHigh.json

You'll see there are 2 regions with the ID "0101". 
It seems there's a shape in the sea area that shouldn't be there.

**Comment by carmoreira** [comment]
It seems there are other issues with the US congressional maps. Most of the issues seem to be repeating IDs of shapes, some seem they are simply separated. Here's a list of issues one of my users came across:

- Florida Low Congressional (FL-26 (1226) not correctly displayed)
- Hawai’i Low Congressional (state display is not standard)
- New Jersey Low Congressional (missing NJ-03 (3403)
- Rhode Island Low Congressional (missing RI-01 (4401) and region name for RI-02 (4402) is incorrect)
- Virginia Low Congressional (VA-02 (5102) missing Virginia Peninsula portion of district)

**Comment by martynasma** [comment]
Fixed in 4.1.22
