### ISSUE TITLE
US Census 2020 and effect on Congressional district maps

### ISSUE THREAD

**Issue by tmorvay** [amcharts/amcharts4-geodata#32]
Hi, 

You may be aware that there was a census taken in the US in 2020. The results also effect the CD's, since they are based on population figures. That results in their being more, or less districts. States also do redistricting, so the district boundaries can change too. I n some states these redistrictings have been taken to court, but with the Congressional elections coming up later in the year (all House seats and 1/3 of the Senate seats on the federal level; also local elections), there are bound to be needs to adjust the data.

Could you communicate a timeline, and if it will be still possible to link to the "old" data, i.e. if you'll have the old set still available, once the new ones are updated? Thanks, Thomas

**Comment by martynasma** [comment]
Thanks for raising this here. We're looking into it.

**Comment by martynasma** [comment]
New Congressional District maps added in version 4.1.24. Just released.

(`region/usa/congressional/2022` folder)
