### ISSUE TITLE
Several maps (159 maps) not exists

### ISSUE THREAD

**Issue by achopijocoder** [amcharts/amcharts4-geodata#4]
We have noticed that all of this maps need to be uploaded to V4. Current applications using all countries maps can not be upgraded until al maps exists on V4. please don't forgive the maps.

1. Cyprus
1. Latvia

1. Lithuania

1. Luxembourg

1. Malta

1. Netherlands

1. Poland

1. Portugal

1. Romania

1. Slovenia

1. Slovakia

1. Sweden

1. Liechtenstein

1. Norway

1. Switzerland

1. Montenegro

1. Macedonia

1. Serbia

1. Turkey

1. Kosovo

1. Bosnia and Herzegovina

1. Moldova

1. Ukraine

1. San Marino

1. Vatican City

1. Monaco

1. Saint Pierre and Miquelon

1. Sint Maarten

1. Turks and Caicos Islands

1. British Virgin Islands

1. US Virgin Islands

1. Antigua and Barbuda

1. Bahamas

1. Barbados

1. Cuba

1. Dominica

1. Grenada

1. Haiti

1. Puerto Rico

1. Saint Kitts and Nevis

1. Saint Lucia

1. Anguilla

1. Cayman Islands

1. Martinique

1. Montserrat

1. Saint Vincent and the Grenadines

1. Guyana

1. Paraguay

1. Peru

1. Trinidad and Tobago

1. Suriname

1. Uruguay

1. Venezuela

1. French Guiana

1. South Georgia and South Sandwich Islands

1. Aruba

1. Curaçao

1. Bonair, Saint Eustachius and Saba

1. Guatemala

1. Nicaragua

1. Panama

1. Morocco

1. Tunisia

1. Libya

1. Sudan

1. Western Sahara

1. Lesotho

1. Namibia

1. Swaziland

1. South Africa

1. Ethiopia

1. Eritrea

1. Somalia

1. Madagascar

1. Mauritius

1. Comoros

1. Seychelles

1. Uganda

1. Rwanda

1. Kenya

1. Tanzania

1. South Sudan

1. Mozambique

1. Malawi

1. Zambia

1. Zimbabwe

1. Benin

1. Côte d'Ivoire

1. Gambia

1. Ghana

1. Guinea-Bissau

1. Liberia

1. Mali

1. Niger

1. Nigeria

1. Senegal

1. Sierra Leone

1. Togo

1. Mauritania

1. Equatorial Guinea

1. Gabon

1. Sao Tome and Principe

1. Saint Helena

1. Afghanistan

1. Saudi Arabia

1. Myanmar

1. Qatar

1. North Korea

1. United Arab Emirates

1. Philippines

1. Indonesia

1. Iraq

1. Iran

1. Jordan

1. Kazakhstan

1. Kyrgyzstan

1. Kuwait

1. Lao People's Democratic Republic

1. Lebanon

1. Malaysia

1. Maldives

1. Mongolia

1. Nepal

1. Oman

1. Pakistan

1. Singapore

1. Syria

1. Sri Lanka

1. Thailand

1. Taiwan

1. Tajikistan

1. Timor-Leste

1. Turkmenistan

1. Uzbekistan

1. Vietnam

1. Yemen

1. Christmas Island

1. Cocos (Keeling) Islands

1. British Indian Ocean Territory

1. Kiribati

1. Marshall Islands

1. Solomon Islands

1. Federated States of Micronesia

1. Nauru

1. New Zealand

1. Palau

1. Papua New Guinea

1. Samoa

1. Tonga

1. Tokelau

1. Vanuatu

1. Guam

1. Cook Islands

1. Northern Mariana Islands

1. Pitcairn Islands

1. Niue

1. Norfolk Island

1. New Caledonia

1. French Polynesia

**Comment by martynasma** [comment]
Thanks for the list.

We're aware that we don't have all the maps available. We're adding them as we go.

Creating a quality map is not as straightforward.

Follow this repo for updates.

**Comment by achopijocoder** [comment]
Thanks for the quick repsonse, Dou you have any due date to have all maps available?

**Comment by wdebusschere** [comment]
@martynasma Any way we can help to create a map? We would like to use the one of Portugal

**Comment by achopijocoder** [comment]
@wdebusschere @martynasma I could help too if you are using guidelines to create. Can be generated from the older version of the maps?

**Comment by martynasma** [comment]
Appreciate the offer guys!

No, these need to be generated from shape files. No way to convert V3 SVGs :(

I'll ask our map team to expedite Portugal. Any more requests?

**Comment by martynasma** [comment]
I mean, besides the 150+ country list from @achopijocoder :D

**Comment by martynasma** [comment]
Heads up. 4.0.22 adds a bunch of missing maps.

We'll continue adding new ones in coming weeks.

**Comment by achopijocoder** [comment]
Good job! :D

**Comment by Azhe403** [comment]
Please add number 111. Indonesia
Thanks!

**Comment by epirir** [comment]
Please! Guatemala.

**Comment by AndrewHucks** [comment]
Any idea when 118 (Laos) will be released?

**Comment by yimej** [comment]
When will USA Territories & Associated States be released?

**Comment by amirhosseinhpv** [comment]
hello, when can we expect iran map be included ?
i really need it !

**Comment by BesoKakulia** [comment]
Hi everybody, [repo]( https://github.com/BesoKakulia/amCharts-missing-geojsons) there are some missing countries from the list (they are low details), hope it will help you :).

**Comment by amirhosseinhpv** [comment]
> 
> 
> Hi everybody, [repo](https://github.com/BesoKakulia/amCharts-missing-geojsons) there are some missing countries from the list (they are low details), hope it will help you :).

Thanks man , it was awesome

**Comment by martynasma** [comment]
We've come a long way since this issue was opened. Most of the maps are now in place. Closing.

**Comment by LC43** [comment]
can this be re-opened? some of these maps are not available.
