### ISSUE TITLE
ArgentinaLow, regions La Rioja and Santa Fe are with the same ID: AR-F

### ISSUE THREAD

**Issue by achopijocoder** [amcharts/amcharts4-geodata#5]
ArgentinaLow.js , has two regions with same ID (AR-F) regions La Rioja and Santa Fe

**Comment by martynasma** [comment]
Thanks for the heads up!

On it.

**Comment by martynasma** [comment]
Just released 4.0.22 which fixes map of Argentina.

Thanks for hanging in!
