### ISSUE TITLE
AsiaLow not contanining Russia

### ISSUE THREAD

**Issue by achopijocoder** [amcharts/amcharts4-geodata#8]
In the map of asiaLow, Russia has only 2 small territories:

![image](https://user-images.githubusercontent.com/13352070/50470784-4c461200-09b2-11e9-8853-8f5b68d6395f.png)

**Comment by martynasma** [comment]
Thanks for the heads up! We're looking for ways to fix that.

**Comment by martynasma** [comment]
Just released 4.0.26 which fixes the issue.

Make sure to clear browser cache.
